@startuml
'https://plantuml.com/class-diagram

namespace SelectStage{
    class SaveDataClass
    class SaveHandler

    class SceneManager
    

    SaveHandler ..> SaveDataClass


    
}

SelectStage.SaveHandler ..> GameAnimal.SaveHandler

namespace GameAnimal{
    class SaveHandler
}

@enduml