@startuml
'https://plantuml.com/class-diagram

namespace Stage{
    namespace Enemy{
        class Move
        interface IMove
        class Attack
        interface IAttack
      
        IMove <|.. Move
        IAttack <|.. Attack

    }
    
    namespace Player{
        class PlayerController
        class ParentMove
        interface IParentMove
        class PlayerView
        interface IPlayerView
        class ChildStatus
        class ParentStatus
        
        IPlayerView <|.. PlayerView
        IParentMove <|.. ParentMove
        
        PlayerController ..> IPlayerView
        PlayerController ..> ParentStatus
        PlayerController ..> ChildStatus
        PlayerController ..> IParentMove
        
    }
    
    namespace Wave{
        class WaveSystem
        interface IWaveSystem
        
        WaveSystem ..> Stage.Enemy.IMove
        WaveSystem ..> Stage.Enemy.IAttack
        IWaveSystem <|.. WaveSystem
        
    }
    
    namespace View{
        class OpenNewStagePopUp
        class ClearPopUp
        class GameOverView
        class BaseView
        
        
    }
    
    class SceneManager
    
    class SoundController
    interface ISoundController
    
    ISoundController <|.. SoundController
    
    SceneManager ..> ISoundController
    SceneManager ..> Stage.Wave.IWaveSystem
}
@enduml